name: Generate connector capabilities

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  calculate-capabilities:
    runs-on: ubuntu-latest
    env:
        BATON_API_KEY: ${{ secrets.BATON_API_KEY }}
        BATON_EMAIL: ${{ secrets.BATON_EMAIL }}
        BATON_ACCOUNT_ID: ${{ secrets.BATON_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELENG_GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -o connector ./cmd/baton-cloudflare-zero-trust

      - name: Run and save output
        run: ./connector capabilities > baton_capabilities.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Updating baton capabilities.'
          add: 'baton_capabilities.json'