name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: go tests
        run: go test -v -covermode=count -json ./... > test.json
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    env:
        BATON_API_KEY: ${{ secrets.BATON_API_KEY }}
        BATON_EMAIL: ${{ secrets.BATON_EMAIL }}
        BATON_ACCOUNT_ID: ${{ secrets.BATON_ACCOUNT_ID }}
        BATON_LOG_LEVEL: 'debug'
        # Revoke grants variable
        CONNECTOR_GRANT: 'role:6ddc5f80969d01105b5a0931e0079365:Analytics:user:9d9a62a5b834a8c9c5cf43cd234dfd4a'
        # Grant entitlements variables
        CONNECTOR_ENTITLEMENT: 'role:6ddc5f80969d01105b5a0931e0079365:Analytics'
        CONNECTOR_PRINCIPAL: '9d9a62a5b834a8c9c5cf43cd234dfd4a'
        CONNECTOR_PRINCIPAL_TYPE: 'user'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-cloudflare-zero-trust
        run: go build ./cmd/baton-cloudflare-zero-trust
      - name: Test grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-cloudflare-zero-trust
          baton-entitlement: role:6ddc5f80969d01105b5a0931e0079365:Analytics
          baton-principal: 9d9a62a5b834a8c9c5cf43cd234dfd4a
          baton-principal-type: user
