name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
        BATON_API_KEY: ${{ secrets.BATON_API_KEY }}
        BATON_EMAIL: ${{ secrets.BATON_EMAIL }}
        BATON_ACCOUNT_ID: ${{ secrets.BATON_ACCOUNT_ID }}
        BATON_AUTH_METHOD: ${{ secrets.BATON_AUTH_METHOD }}
        BATON_LOG_LEVEL: 'debug'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-cloudflare-zero-trust
        run: go build ./cmd/baton-cloudflare-zero-trust
      - name: Test grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-cloudflare-zero-trust
          baton-entitlement: ${{ vars.ROLE_ENTITLEMENT }}
          baton-principal: ${{ vars.USER_PRINCIPAL }}
          baton-principal-type: ${{ vars.USER_PRINCIPAL_TYPE }}
