name: tests
on: 
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
        BATON_API_KEY: ${{ secrets.BATON_API_KEY }}
        BATON_EMAIL: ${{ secrets.BATON_EMAIL }}
        BATON_ACCOUNT_ID: ${{ secrets.BATON_ACCOUNT_ID }}
        BATON_LOG_LEVEL: 'debug'
        # Revoke grants variable
        REVOKE_GRANT: ''
        # Grant entitlements variables
        GRANT_ENTITLEMENT: ''
        GRANT_PRINCIPAL: ''
        GRANT_PRINCIPAL_TYPE: ''

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build baton-cloudflare-zero-trust
        run: go build ./cmd/baton-cloudflare-zero-trust
      - name: Run baton-cloudflare-zero-trust-cmd
        run: ./baton-cloudflare-zero-trust
      - name: Revoke grants
        if: env.REVOKE_GRANT != ''
        run: |
          echo "Syncing resources..."
          ./baton-cloudflare-zero-trust
          echo "Testing revoking"
          ./baton-cloudflare-zero-trustt --log-level=debug --revoke-grant ${{ env.REVOKE_GRANT }}
      - name: Grant entitlements
        if: ${{ env.GRANT_ENTITLEMENT }} != '' && ${{ env.GRANT_PRINCIPAL }} != '' && ${{ env.GRANT_PRINCIPAL_TYPE }} != ''
        run: |
          echo "Syncing resources..."
          ./baton-cloudflare-zero-trust
          echo "Testing provisioning"
          ./baton-cloudflare-zero-trust --log-level=debug  --grant-entitlement ${{ env.GRANT_ENTITLEMENT }} --grant-principal ${{ env.GRANT_PRINCIPAL }} --grant-principal-type ${{ env.GRANT_PRINCIPAL_TYPE }}
      - name: List Resources
        run: docker run --rm -v $(pwd):/out ghcr.io/conductorone/baton:latest -f "/out/sync.c1z" resources